server:
  port: 8001

spring:
  application:
    name: finance-ms
  jmx:
    enabled: false
  datasource:
    url: jdbc:h2:mem:financedb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2